apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorizationmicroservicepas-deployment
  labels:
    app: AuthorizationMicroservicePAS
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuthorizationMicroservicePAS	  
  template:
    metadata:
      labels:
        app: AuthorizationMicroservicePAS
    spec:
      containers:
      - name: authorizationmicroservicepas
        image: policyadministrationsystem.azurecr.io/authorizationmicroservice:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: authsecret
---
apiVersion: v1
kind: Service
metadata:
  name: authorizationmicroservicepasservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuthorizationMicroservicePAS